
select CUSTOMER_ID,APPLIANCE_TYPE_CODE ,NEW_APPLIANCE_QNT_BILLCAL QUANTITY from BURNER_QNT_CHANGE BQC
WHERE CUSTOMER_ID IN (
SELECT CUSTOMER_ID FROM CUSTOMER_CONNECTION
WHERE CUSTOMER_ID like '02%'
AND STATUS = 2 )
ORDER BY CUSTOMER_ID ASC