
select * from SALES_REPORT
where SUBSTR(CUSTOMER_ID,3,2) ='01'
 AND BILLING_YEAR = 2018
 and TOTAL_AMOUNT <> VALUE_OF_ACTUAL_CONSUMPTION
 
 
 UPDATE SALES_REPORT SET TOTAL_ACTUAL_CONSUMPTION=ROUND(TOTAL_AMOUNT/RATE,2)
 where SUBSTR(CUSTOMER_ID,3,2) ='09'
 AND BILLING_YEAR = 2018
 and TOTAL_ACTUAL_CONSUMPTION = VALUE_OF_ACTUAL_CONSUMPTION
 