--REDUCING POSITIVE BALANCE
UPDATE BILL_METERED
SET PAYABLE_AMOUNT = COLLECTED_AMOUNT
WHERE CUSTOMER_ID like '190200019%'
AND PAYABLE_AMOUNT>COLLECTED_AMOUNT;

--REDUCING NEGETIVE BALANCE
UPDATE BILL_METERED
SET  COLLECTED_AMOUNT = PAYABLE_AMOUNT
WHERE CUSTOMER_ID like '190200019%'
AND PAYABLE_AMOUNT<COLLECTED_AMOUNT;