SELECT bnm.CUSTOMER_ID,
       bnm.BILL_ID,
       MON || ', ' || BILL_YEAR DESCRIPTION,
       BILLED_AMOUNT,
       ACTUAL_SURCHARGE SURCHARGE_AMOUNT,
       COLLECTED_PAYABLE_AMOUNT - NVL (COLLECTED_SURCHARGE, 0)
          COLLECTED_BILLED_AMOUNT,
       NVL (COLLECTED_SURCHARGE, 0) COLLECTED_SURCHARGE,
       TO_CHAR (DUE_DATE, 'dd-mm-rrrr') DUE_DATE,
       getBankBranch (BRANCH_ID) BANK_NAME,
       TO_CHAR (bnm.COLLECTION_DATE) COLLECTION_DATE
  FROM bill_non_metered bnm, MST_MONTH mm
 WHERE     BNM.BILL_MONTH = MM.M_ID
       AND bnm.CUSTOMER_ID = '010110723'
       AND BILL_MONTH = 10
       AND BILL_YEAR = 2017